# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2396037d02ea0088a43ef42ad00f84dd8d0bf34231f8da1654d2e8500ed2e94b8b51648bd6804b556ce881b1cfb5d481fccacd5cb0542018cfa7fbf4bfb63f71

test:
  secret_key_base: ba84aa478e965499b7a5b871c4888dd539ebdbb0e24b6a8d5b0757aeece71632d1b2eb9223f501e757f15fd3787918fad5875c046e5d033e6a0e4e33af5f47de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
